[project]
name = "geedrive"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.136.3",
    "pydantic[email]>=2.13.4",
    "pydantic-settings>=2.14.1",
    "supabase>=2.30.0",
    "uvicorn[standard]>=0.48.0",
    "python-multipart>=0.0.29",
    "pytest>=9.0.3",
    "httpx>=0.28.1",
    "pydantic-extra-types[phonenumbers]>=2.11.1",
]

